name: Build & Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run build
        run: ./gradlew build
      - name: Run tests
        run: ./gradlew test

      - uses: actions/upload-artifact@v4
        with:
          name: tgbridge
          path: build/release/*.jar
  e2e:
    name: End-to-end tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: |
            8
            21
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - uses: actions/download-artifact@v4
        with:
          name: tgbridge
          path: build/release/
      - uses: actions/cache@v4
        with:
          path: |
            tests/run/**
            !tests/run/*/world/**
            !tests/run/*/crash-reports/**
            !tests/run/*/logs/**
            !tests/run/**.log
          key: tests-${{ hashFiles('tests/src/**') }}

      - name: Run tests
        working-directory: tests
        run: deno run -A src/main.ts --no-build
